= OldPhone Coding Challenge
Benjamin Neustadt
:source-highlighter: csharp
:document-type: article
:toc:

The class `oldphone` takes a string as an argument and returns the correct output corresponding to number inputs, using the Translate method.
****
*See the Ruby answer to this exercise https://github.com/BenjaminNeustadt/OldPhone[here].*
****

== Usage

.*Installation*

****
* https://dotnet.microsoft.com/en-us/download[Download] the .NET SDK

* Git clone this repository:
----
 git clone https://github.com/BenjaminNeustadt/OldPhone_csharp.git
----

* `cd` into the repository

* Install the charp repl:
----
 dotnet tool install -g csharprepl
----

* You can only add it to the current session by running the following command:
----
export PATH="$PATH:/Users/[username]/.dotnet/tools"
----

* To use the repl:
----
csharprepl
----

* `cd` to OldPhone/ directory

* Add the PackageReference for the package 'FluentAssertions' into the project: 
----
dotnet add package FluentAssertions --version 6.7.0
----

* Run the tests:
----
 dotnet test
----
****

== Process Thoughts

As this was a first exercise in C# it was first done in Ruby which I am more familiar with.

****
*See the Ruby answer to this exercise https://github.com/BenjaminNeustadt/OldPhone[here].*
****

Currently, the C# version is made up of a class and 4 methods. There are still areas where I would like to refactor things, and I think it could certainly be more elegant in many places. 
The next step I will take is refactoring, and I would perhaps like to try this again using different System methods instead of those currently used.

As a testing framework I chose to use https://xunit.net/[Xunit] as it is more in line with the Test Driven Development https://stackoverflow.com/a/40220724[process].
I imported https://fluentassertions.com/introduction[Fluentassertions] which uses more idiomatic language syntax whilst using the testing framweorks.
The C# https://learn.microsoft.com/en-us/dotnet/csharp/[documentation] is very thorough, though I used https://kapeli.com/dash[Dash] to consult most documentation, as I find it more intuitive with its search functionality, and lack of visual noise.

The C# community seems to have a great sense of humour which made it more enjoyable also.

This was my first experience with proper https://stackoverflow.com/a/14946078[type safety], I found it enjoyable. The error messages are very informative.
Test driving this helped with the incremental learning. Using the https://lioncoding.com/csharprepl-the-magic-command-line-c-repl/[csharp REPL] was an invaluable tool in being able to learn what can and can't be done.

== Original Instructions

[.text-center]
****

[source, markdown]
----
┌───────┬───────┬───────┐
│       │       │       │
│   1   │   2   │   3   │
│  &'(  │  ABC  │  DEF  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   4   │   5   │   6   │
│  GHI  │  JKL  │  MNO  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   7   │   8   │   9   │
│ PQRS  │  TUV  │ WXYZ  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   *   │   0   │   #   │
│   ←   │   ␣   │   →   │
└───────┴───────┴───────┘
----

****

Here is an old phone keypad with alphabetical letters, a
backspace key, and a send button.

Each button has a number to identify it and pressing a button multiple
times will cycle through the letters on it allowing each button to
represent more than one letter.

For example, pressing 2 once will return ‘A’ but pressing twice in
succession will return ‘B’.

You must pause for a second in order to type two characters from the
same button after each other: “222 2 22” -> “CAB”.


****
.*The Directions*
[source, md]
----
Please design and document a class of method that will turn any input to <1>
OldPhonePad into the correct output.
Assume that a send (represented as a literally the _#_) will always be included at the end of every input. <2>
----
<1> Is the "class of method" supposed to read "class or method"?
    This word, I think should be "or" instead, and I have applied this assumption before I have asked for confirmation.
<2> What to do if additional information is found after the "send" is described in the writing below.

As an unspecified behaviour,
if we reach the pound sign and find more characters after that pound sign
(the signal to send) we will send everything up until then,
and ignore any input after that signal.

****

----
public static String OldPhonePad (string input) {
// Please write your implementation here!
}
----

== *Examples:*

Input - Output:

[source, csharp]
----
OldPhonePad(“33#”) => output: E
OldPhonePad(“227*#”) => output: B
OldPhonePad(“4433555 555666#”) => output: HELLO
OldPhonePad(“443355 55666#”) => output: HEKKO
OldPhonePad(“8 88777444666*664#”) => output: ?????
----

== Approach

=== key-pad values

|===
| sequence letter | sequence letter | sequence letter

^| 1 &  ^| 11 '  ^| 111 (
^| 2 a  ^| 22 b  ^| 222 c
^| 3 d  ^| 33 e  ^| 333 f

^| 4 g  ^| 44 h  ^| 444 i
^| 5 j  ^| 55 k  ^| 555 l
^| 6 m  ^| 66 n  ^| 666 o

^| 7 p  ^| 77 q  ^| 777 r 7777 s
^| 8 t  ^| 88 u  ^| 888 v
^| 9 w  ^| 99 x  ^| 999 y 9999 z

|===
