= OldPhone Coding Challenge
Benjamin Neustadt
:source-highlighter: csharp
:document-type: article
// URLs:
:url-dash-download: https://kapeli.com/dash
:url-dotnet-download: https://dotnet.microsoft.com/en-us/download
:url-csharp-doc: https://learn.microsoft.com/en-us/dotnet/csharp/
:url-csharp-docs: https://learn.microsoft.com/en-us/dotnet/csharp/?WT.mc_id=dotnet-35129-website
:url-csharp-repl: https://lioncoding.com/csharprepl-the-magic-command-line-c-repl/
:url-fluentassertions: https://fluentassertions.com/introduction
:url-ruby-version: https://github.com/BenjaminNeustadt/OldPhone
:url-stackoverflow-tdd: https://stackoverflow.com/a/40220724
:url-stackoverflow-type-safety: https://stackoverflow.com/a/14946078
:url-xunit: https://xunit.net/

:toc:

OldPhonePad is a program to decode number values using the same digit into their correlating letter, punctuation and space values.
The class `OldPhonePad` takes a string as an argument and returns the correct output corresponding to number inputs, using the `Translate` method.
****
*See the Ruby answer to this exercise {url-ruby-version}[here].*
****

Key documentation

* {url-csharp-docs}[C# Documentation]
* {url-csharp-repl}[C# REPL]


== Usage

.*Installation*

****
* {url-dotnet-download}[Download] the .NET SDK

* Git clone this repository:
----
 git clone https://github.com/BenjaminNeustadt/OldPhone_csharp.git
----

* `cd` into the repository

* Install the charp repl:
----
 dotnet tool install -g csharprepl
----

* You can only add it to the current session by running the following command:
----
export PATH="$PATH:/Users/[username]/.dotnet/tools"
----

* To use the repl:
----
csharprepl
----

* `cd` to OldPhone/ directory

* Add the PackageReference for the package 'FluentAssertions' into the project: 
----
dotnet add package FluentAssertions --version 6.7.0
----

* Run the tests:
----
 dotnet test
----
****

== Process Thoughts

As this was a first exercise in C# it was first done in Ruby which I am more familiar with.

****
*See the Ruby answer to this exercise {url-ruby-version}[here].*
****

Currently, the C# version is made up of a class and 4 methods. There are still areas where refactoring is required, and certain lines can be more elegant. 
The next step to be taken is refactoring, and perhaps trying certain things again using different System methods instead of those currently used (i.e. using `Regex.Match()` instead of `Regex.Split()`).

{url-xunit}[Xunit] was chosen as the testing framework, as it is more in line with the Test Driven Development {url-stackoverflow-tdd}[process].
{url-fluentassertions}[Fluentassertions] is used for more idiomatic language syntax whilst using the testing framweork. The error messages are also very informative.

The C# {url-csharp-doc}[documentation] is very thorough, though {url-dash-download}[Dash] is recommended to consult the documentation, as it is more intuitive with its search functionality, and lack of visual noise.

The C# community seems to have a great sense of humour which has made it more enjoyable also.
This was a first experience with proper {url-stackoverflow-type-safety}[type safety], I found it enjoyable. 
Test driving this helped with the incremental learning. Using the {url-csharp-repl}[csharp REPL] was an invaluable tool in being able to learn what can and can't be done.


One caveat is that I am not able to load this into the repl, as it seems the current documentation is limited in the support of mac users in this regard (cannot use .exe files).
I attempted to write a .csx file and use `#load`, though encountered some difficulty in this area.

== Original Instructions

[.text-center]
****

[source, markdown]
----
┌───────┬───────┬───────┐
│       │       │       │
│   1   │   2   │   3   │
│  &'(  │  ABC  │  DEF  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   4   │   5   │   6   │
│  GHI  │  JKL  │  MNO  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   7   │   8   │   9   │
│ PQRS  │  TUV  │ WXYZ  │
│       │       │       │
├───────┼───────┼───────┤
│       │       │       │
│   *   │   0   │   #   │
│   ←   │   ␣   │   →   │
└───────┴───────┴───────┘
----

****

Here is an old phone keypad with alphabetical letters, a
backspace key, and a send button.

Each button has a number to identify it and pressing a button multiple
times will cycle through the letters on it allowing each button to
represent more than one letter.

For example, pressing 2 once will return ‘A’ but pressing twice in
succession will return ‘B’.

You must pause for a second in order to type two characters from the
same button after each other: “222 2 22” -> “CAB”.


****
.*The Directions*
[source, md]
----
Please design and document a class of method that will turn any input to <1>
OldPhonePad into the correct output.
Assume that a send (represented as a literally the _#_) will always be included at the end of every input. <2>
----
<1> Is the "class of method" supposed to read "class or method"?
    This word, I think should be "or" instead, and I have applied this assumption before I have asked for confirmation.
<2> What to do if additional information is found after the "send" is described in the writing below.

As an unspecified behaviour,
if we reach the pound sign and find more characters after that pound sign
(the signal to send) we will send everything up until then,
and ignore any input after that signal.

****

----
public static String OldPhonePad (string input) {
// Please write your implementation here!
}
----

== *Examples:*

Input - Output:

[source, csharp]
----
OldPhonePad(“33#”) => output: E
OldPhonePad(“227*#”) => output: B
OldPhonePad(“4433555 555666#”) => output: HELLO
OldPhonePad(“443355 55666#”) => output: HEKKO
OldPhonePad(“8 88777444666*664#”) => output: ?????
----

== Approach

=== key-pad values

|===
| sequence letter | sequence letter | sequence letter

^| 1 &  ^| 11 '  ^| 111 (
^| 2 a  ^| 22 b  ^| 222 c
^| 3 d  ^| 33 e  ^| 333 f

^| 4 g  ^| 44 h  ^| 444 i
^| 5 j  ^| 55 k  ^| 555 l
^| 6 m  ^| 66 n  ^| 666 o

^| 7 p  ^| 77 q  ^| 777 r 7777 s
^| 8 t  ^| 88 u  ^| 888 v
^| 9 w  ^| 99 x  ^| 999 y 9999 z

|===
